// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxwudkbfxuhyjjkdwfgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4d3Vka2JmeHVoeWpqa2R3ZmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODA0OTYsImV4cCI6MjA3MTQ1NjQ5Nn0.IGOR1_ac114Ueja90tjSORf3rf8TViQn-OAS65_3juU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});